In [ ]:
# Step 1: Import necessary libraries and load the dataset
import pandas as pd  # pandas is used for data manipulation and analysis
import numpy as np   # numpy is used for numerical operations

# Load the dataset
df = pd.read_csv("Real_estate.csv")  # Reads the CSV file and loads it into a pandas DataFrame

# Clean column names by removing spaces and special characters
print('column names before cleaning : ',df.columns)
df.columns = df.columns.str.replace(' ', '_').str.replace('[^A-Za-z0-9_]', '')  # Removes spaces and special characters from column names
df.columns = df.columns.str.lower()  # Converts all column names to lowercase for consistency
print('column names after cleaning : \n',df.columns)

# Step 2: Handle missing values
print("Missing values before handling : ",df.isnull().sum())  # Check for missing values in each column

# If there are missing values, choose a strategy to handle them
# In this case, we'll use imputation for numerical columns with the median value
df.fillna(df.median(), inplace=True)  # Fill missing numerical values with the median value

# Verify that missing values have been handled
print("Missing values after handling : \n",df.isnull().sum())  # Check again for missing values

# Step 3: Perform data merging (if relevant datasets are available)
# Example: neighborhood_df = pd.read_csv("neighborhood_data.csv")
# df = pd.merge(df, neighborhood_df, on='neighborhood', how='left')

# For this example, we skip merging as no additional dataset is provided.

# Step 4: Filter data based on specific criteria
# Filter properties that were sold in 2013 or later
df_filtered = df[df['x1_transaction_date'] >= 2013]
print("Filtered data based on transaction date:")
print(df_filtered.head())

# Step 5: Handle categorical variables (if any)
# For example, assume 'property_type' is a categorical column
# Apply one-hot encoding to convert categorical variables into numerical format
df_encoded = pd.get_dummies(df, drop_first=True)  # One-hot encoding (drop_first avoids multicollinearity)
# This method transforms each category of a column into a separate binary (0 or 1) column.
#  For example, if you have a column called Color with values ['Red', 'Green', 'Blue'], it will be transformed into three separate columns:
# Color_Red, Color_Green, Color_Blue
# If the original value in the Color column is Red, the row will have 1 in the Color_Red column and 0 in the others.

# By setting drop_first=True, we drop the first category in each categorical feature column.
# For example, if you have ['Red', 'Green', 'Blue'] as categories in a column, with drop_first=True, only ['Green', 'Blue'] will be kept.
#  This means if both Color_Green and Color_Blue are 0, then the value must be Red.
# This is done to avoid multicollinearity (when two or more features are highly correlated, which can lead to problems in some machine learning models).
print("Encoded dataset:")
print(df_encoded.head())

# Step 6: Aggregate data to calculate summary statistics
# Calculate the average sale price by house age
avg_sale_price_by_age = df.groupby('x2_house_age')['y_house_price_of_unit_area'].mean().reset_index()
# This groups the data by the column 'x2_house_age'
# After grouping by the 'x2_house_age' column, this selects the 'y_house_price_of_unit_area' column within each group.
# This calculates the mean (average) of 'y_house_price_of_unit_area' for each group of 'x2_house_age'.
# The reset_index() function is used to reset the index of the resulting DataFrame,
#  turning the grouped column (x2_house_age) back into a regular column instead of keeping it as an index.
print("Average sale price by house age:")
print(avg_sale_price_by_age)

# Step 7: Identify and handle outliers
# Calculate Z-scores for each numerical column to detect outliers
from scipy.stats import zscore  # Importing zscore function to detect outliers 

df_zscore = df.select_dtypes(include=[np.number])  # Select only numerical columns
z_scores = np.abs(zscore(df_zscore))  # Calculate absolute Z-scores

# Set a threshold (e.g., Z-score > 3 is considered an outlier)
outliers = (z_scores > 3).all(axis=1)  # Identify rows with outliers in all columns

# Remove rows with outliers
df_no_outliers = df[~outliers]
print("Dataset after removing outliers:")
print(df_no_outliers.head())

column names before cleaning :  Index(['No', 'X1 transaction date', 'X2 house age',
       'X3 distance to the nearest MRT station',
       'X4 number of convenience stores', 'X5 latitude', 'X6 longitude',
       'Y house price of unit area'],
      dtype='object')
column names after cleaning :
 Index(['no', 'x1_transaction_date', 'x2_house_age',
       'x3_distance_to_the_nearest_mrt_station',
       'x4_number_of_convenience_stores', 'x5_latitude', 'x6_longitude',
       'y_house_price_of_unit_area'],
      dtype='object')
Missing values before handling :  no                                        0
x1_transaction_date                       0
x2_house_age                              0
x3_distance_to_the_nearest_mrt_station    0
x4_number_of_convenience_stores           0
x5_latitude                               0
x6_longitude                              0
y_house_price_of_unit_area                0
dtype: int64
Missing values after handling :
 no                                        0
x1_transaction_date                       0
x2_house_age                              0
x3_distance_to_the_nearest_mrt_station    0
x4_number_of_convenience_stores           0
x5_latitude                               0
x6_longitude                              0
y_house_price_of_unit_area                0
dtype: int64
Filtered data based on transaction date:
   no  x1_transaction_date  x2_house_age  \
2   3             2013.583          13.3
3   4             2013.500          13.3
7   8             2013.417          20.3
8   9             2013.500          31.7
9  10             2013.417          17.9

   x3_distance_to_the_nearest_mrt_station  x4_number_of_convenience_stores  \
2                                561.9845                                5
3                                561.9845                                5
7                                287.6025                                6
8                               5512.0380                                1
9                               1783.1800                                3

   x5_latitude  x6_longitude  y_house_price_of_unit_area
2     24.98746     121.54391                        47.3
3     24.98746     121.54391                        54.8
7     24.98042     121.54228                        46.7
8     24.95095     121.48458                        18.8
9     24.96731     121.51486                        22.1
Encoded dataset:
   no  x1_transaction_date  x2_house_age  \
0   1             2012.917          32.0
1   2             2012.917          19.5
2   3             2013.583          13.3
3   4             2013.500          13.3
4   5             2012.833           5.0

   x3_distance_to_the_nearest_mrt_station  x4_number_of_convenience_stores  \
0                                84.87882                               10
1                               306.59470                                9
2                               561.98450                                5
3                               561.98450                                5
4                               390.56840                                5

   x5_latitude  x6_longitude  y_house_price_of_unit_area
0     24.98298     121.54024                        37.9
1     24.98034     121.53951                        42.2
2     24.98746     121.54391                        47.3
3     24.98746     121.54391                        54.8
4     24.97937     121.54245                        43.1
Average sale price by house age:
     x2_house_age  y_house_price_of_unit_area
0             0.0                   54.135294
1             1.0                   50.700000
2             1.1                   49.780000
3             1.5                   48.700000
4             1.7                   50.400000
..            ...                         ...
231          40.9                   54.350000
232          41.3                   47.900000
233          41.4                   63.300000
234          42.7                   35.300000
235          43.8                   42.700000

[236 rows x 2 columns]
Dataset after removing outliers:
   no  x1_transaction_date  x2_house_age  \
0   1             2012.917          32.0
1   2             2012.917          19.5
2   3             2013.583          13.3
3   4             2013.500          13.3
4   5             2012.833           5.0

   x3_distance_to_the_nearest_mrt_station  x4_number_of_convenience_stores  \
0                                84.87882                               10
1                               306.59470                                9
2                               561.98450                                5
3                               561.98450                                5
4                               390.56840                                5

   x5_latitude  x6_longitude  y_house_price_of_unit_area
0     24.98298     121.54024                        37.9
1     24.98034     121.53951                        42.2
2     24.98746     121.54391                        47.3
3     24.98746     121.54391                        54.8
4     24.97937     121.54245                        43.1

C:\Users\HP\AppData\Local\Temp\ipykernel_17532\2714425529.py:11: FutureWarning: The default value of regex will change from True to False in a future version.
  df.columns = df.columns.str.replace(' ', '_').str.replace('[^A-Za-z0-9_]', '')  # Removes spaces and special characters from column names